name: Run PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  run-powershell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Write-Host "Release Name: ${{ github.event.release.name }}, jobname: $env:GITHUB_JOB and RunId: $env:GITHUB_RUN_ID, Attemps: $env:GITHUB_RUN_ATTEMPT"         
          $LogFileName = ${{ secrets.CustomerName }} + "_" + "${{ github.workflow }}" + "_" +  "$env:GITHUB_RUN_ID"
          $LogFilepath = "$Home\" + $LogFileName + ".txt"
          Start-Transcript -Path $LogFilepath -Append -IncludeInvocationHeader
          Write-Host "Attempt Number: $env:GITHUB_RUN_ATTEMPT"
        azPSVersion: "latest"
