name: Run PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  run-powershell-script:
    runs-on: windows-latest
    steps:
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Write-Host "Release Name: ${{ github.event.release.name }}, jobname: $env:GITHUB_JOB and RunId: $env:GITHUB_RUN_ID, Attemps: $env:GITHUB_RUN_ATTEMPT"         
          $LogFileName = "${{ secrets.CustomerName }}" + "_" + "${{ github.workflow }}" + "_" +  $env:GITHUB_RUN_ID
          $LogFilepath = "$Home\" + $LogFileName + ".txt"
          Start-Transcript -Path $LogFilepath -Append -IncludeInvocationHeader -NoClobber
          Write-Host "Attempt Number: $env:GITHUB_RUN_ATTEMPT"
          Write-Host "test the transcript logic."
          Get-Content -Path $LogFilepath
        azPSVersion: "latest"
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: $LogFileName
