name: Run PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  run-powershell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Write-Host "Release Name: ${{ github.event.release.name }}, jobname: $env:GITHUB_JOB and RunId: $env:GITHUB_RUN_ID"
          $runId = $env:GITHUB_RUN_ID
          $jobName = $env:GITHUB_JOB
          $url = "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/$runId/jobs"
          $accessToken = ${{ secrets.BY_PAT_Token }}
          $headers = @{
          "Authorization" = "Bearer $accessToken"
          }
          $jobs = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
          $attempts = $jobs.jobs | Where-Object { $_.name -eq $jobName } | Measure-Object
          Write-Host "Attempt Count: $($attempts)}"
        azPSVersion: "latest"
